// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.6
// source: dfs.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	MetaService_UploadRequest_FullMethodName      = "/dfs.v1.MetaService/UploadRequest"
	MetaService_DeleteRequest_FullMethodName      = "/dfs.v1.MetaService/DeleteRequest"
	MetaService_ListFiles_FullMethodName          = "/dfs.v1.MetaService/ListFiles"
	MetaService_GetFile_FullMethodName            = "/dfs.v1.MetaService/GetFile"
	MetaService_AllocateChunks_FullMethodName     = "/dfs.v1.MetaService/AllocateChunks"
	MetaService_GetChunksLocations_FullMethodName = "/dfs.v1.MetaService/GetChunksLocations"
)

// MetaServiceClient is the client API for MetaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetaServiceClient interface {
	// Uploadrequest stores new file metadata to metaservice table
	UploadRequest(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error)
	// Deleterequest deletes file metadata of given file
	DeleteRequest(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
	AllocateChunks(ctx context.Context, in *AllocateChunksRequest, opts ...grpc.CallOption) (*AllocateChunksResponse, error)
	GetChunksLocations(ctx context.Context, in *GetChunkLocationRequest, opts ...grpc.CallOption) (*GetChunkLocationResponse, error)
}

type metaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetaServiceClient(cc grpc.ClientConnInterface) MetaServiceClient {
	return &metaServiceClient{cc}
}

func (c *metaServiceClient) UploadRequest(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadFileResponse)
	err := c.cc.Invoke(ctx, MetaService_UploadRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaServiceClient) DeleteRequest(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, MetaService_DeleteRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaServiceClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, MetaService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaServiceClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileResponse)
	err := c.cc.Invoke(ctx, MetaService_GetFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaServiceClient) AllocateChunks(ctx context.Context, in *AllocateChunksRequest, opts ...grpc.CallOption) (*AllocateChunksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocateChunksResponse)
	err := c.cc.Invoke(ctx, MetaService_AllocateChunks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaServiceClient) GetChunksLocations(ctx context.Context, in *GetChunkLocationRequest, opts ...grpc.CallOption) (*GetChunkLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChunkLocationResponse)
	err := c.cc.Invoke(ctx, MetaService_GetChunksLocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaServiceServer is the server API for MetaService service.
// All implementations must embed UnimplementedMetaServiceServer
// for forward compatibility
type MetaServiceServer interface {
	// Uploadrequest stores new file metadata to metaservice table
	UploadRequest(context.Context, *UploadFileRequest) (*UploadFileResponse, error)
	// Deleterequest deletes file metadata of given file
	DeleteRequest(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error)
	AllocateChunks(context.Context, *AllocateChunksRequest) (*AllocateChunksResponse, error)
	GetChunksLocations(context.Context, *GetChunkLocationRequest) (*GetChunkLocationResponse, error)
	mustEmbedUnimplementedMetaServiceServer()
}

// UnimplementedMetaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMetaServiceServer struct {
}

func (UnimplementedMetaServiceServer) UploadRequest(context.Context, *UploadFileRequest) (*UploadFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadRequest not implemented")
}
func (UnimplementedMetaServiceServer) DeleteRequest(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRequest not implemented")
}
func (UnimplementedMetaServiceServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedMetaServiceServer) GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedMetaServiceServer) AllocateChunks(context.Context, *AllocateChunksRequest) (*AllocateChunksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocateChunks not implemented")
}
func (UnimplementedMetaServiceServer) GetChunksLocations(context.Context, *GetChunkLocationRequest) (*GetChunkLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChunksLocations not implemented")
}
func (UnimplementedMetaServiceServer) mustEmbedUnimplementedMetaServiceServer() {}

// UnsafeMetaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetaServiceServer will
// result in compilation errors.
type UnsafeMetaServiceServer interface {
	mustEmbedUnimplementedMetaServiceServer()
}

func RegisterMetaServiceServer(s grpc.ServiceRegistrar, srv MetaServiceServer) {
	s.RegisterService(&MetaService_ServiceDesc, srv)
}

func _MetaService_UploadRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).UploadRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaService_UploadRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).UploadRequest(ctx, req.(*UploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaService_DeleteRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).DeleteRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaService_DeleteRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).DeleteRequest(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaService_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaService_GetFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).GetFile(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaService_AllocateChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateChunksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).AllocateChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaService_AllocateChunks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).AllocateChunks(ctx, req.(*AllocateChunksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaService_GetChunksLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChunkLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).GetChunksLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaService_GetChunksLocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).GetChunksLocations(ctx, req.(*GetChunkLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetaService_ServiceDesc is the grpc.ServiceDesc for MetaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dfs.v1.MetaService",
	HandlerType: (*MetaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadRequest",
			Handler:    _MetaService_UploadRequest_Handler,
		},
		{
			MethodName: "DeleteRequest",
			Handler:    _MetaService_DeleteRequest_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _MetaService_ListFiles_Handler,
		},
		{
			MethodName: "GetFile",
			Handler:    _MetaService_GetFile_Handler,
		},
		{
			MethodName: "AllocateChunks",
			Handler:    _MetaService_AllocateChunks_Handler,
		},
		{
			MethodName: "GetChunksLocations",
			Handler:    _MetaService_GetChunksLocations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dfs.proto",
}

const (
	DataNodeService_WriteChunk_FullMethodName  = "/dfs.v1.DataNodeService/WriteChunk"
	DataNodeService_ReadChunk_FullMethodName   = "/dfs.v1.DataNodeService/ReadChunk"
	DataNodeService_DeleteChunk_FullMethodName = "/dfs.v1.DataNodeService/DeleteChunk"
)

// DataNodeServiceClient is the client API for DataNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataNodeServiceClient interface {
	WriteChunk(ctx context.Context, opts ...grpc.CallOption) (DataNodeService_WriteChunkClient, error)
	ReadChunk(ctx context.Context, in *ChunkReadRequest, opts ...grpc.CallOption) (DataNodeService_ReadChunkClient, error)
	// DeleteChunk deletes a chunk from the data node
	DeleteChunk(ctx context.Context, in *DeleteChunkRequest, opts ...grpc.CallOption) (*DeleteChunkResponse, error)
}

type dataNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataNodeServiceClient(cc grpc.ClientConnInterface) DataNodeServiceClient {
	return &dataNodeServiceClient{cc}
}

func (c *dataNodeServiceClient) WriteChunk(ctx context.Context, opts ...grpc.CallOption) (DataNodeService_WriteChunkClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataNodeService_ServiceDesc.Streams[0], DataNodeService_WriteChunk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &dataNodeServiceWriteChunkClient{ClientStream: stream}
	return x, nil
}

type DataNodeService_WriteChunkClient interface {
	Send(*ChunkWriteRequest) error
	CloseAndRecv() (*ChunkWriteResponse, error)
	grpc.ClientStream
}

type dataNodeServiceWriteChunkClient struct {
	grpc.ClientStream
}

func (x *dataNodeServiceWriteChunkClient) Send(m *ChunkWriteRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dataNodeServiceWriteChunkClient) CloseAndRecv() (*ChunkWriteResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ChunkWriteResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dataNodeServiceClient) ReadChunk(ctx context.Context, in *ChunkReadRequest, opts ...grpc.CallOption) (DataNodeService_ReadChunkClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataNodeService_ServiceDesc.Streams[1], DataNodeService_ReadChunk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &dataNodeServiceReadChunkClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DataNodeService_ReadChunkClient interface {
	Recv() (*ChunkReadResponse, error)
	grpc.ClientStream
}

type dataNodeServiceReadChunkClient struct {
	grpc.ClientStream
}

func (x *dataNodeServiceReadChunkClient) Recv() (*ChunkReadResponse, error) {
	m := new(ChunkReadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dataNodeServiceClient) DeleteChunk(ctx context.Context, in *DeleteChunkRequest, opts ...grpc.CallOption) (*DeleteChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteChunkResponse)
	err := c.cc.Invoke(ctx, DataNodeService_DeleteChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataNodeServiceServer is the server API for DataNodeService service.
// All implementations must embed UnimplementedDataNodeServiceServer
// for forward compatibility
type DataNodeServiceServer interface {
	WriteChunk(DataNodeService_WriteChunkServer) error
	ReadChunk(*ChunkReadRequest, DataNodeService_ReadChunkServer) error
	// DeleteChunk deletes a chunk from the data node
	DeleteChunk(context.Context, *DeleteChunkRequest) (*DeleteChunkResponse, error)
	mustEmbedUnimplementedDataNodeServiceServer()
}

// UnimplementedDataNodeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDataNodeServiceServer struct {
}

func (UnimplementedDataNodeServiceServer) WriteChunk(DataNodeService_WriteChunkServer) error {
	return status.Errorf(codes.Unimplemented, "method WriteChunk not implemented")
}
func (UnimplementedDataNodeServiceServer) ReadChunk(*ChunkReadRequest, DataNodeService_ReadChunkServer) error {
	return status.Errorf(codes.Unimplemented, "method ReadChunk not implemented")
}
func (UnimplementedDataNodeServiceServer) DeleteChunk(context.Context, *DeleteChunkRequest) (*DeleteChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteChunk not implemented")
}
func (UnimplementedDataNodeServiceServer) mustEmbedUnimplementedDataNodeServiceServer() {}

// UnsafeDataNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataNodeServiceServer will
// result in compilation errors.
type UnsafeDataNodeServiceServer interface {
	mustEmbedUnimplementedDataNodeServiceServer()
}

func RegisterDataNodeServiceServer(s grpc.ServiceRegistrar, srv DataNodeServiceServer) {
	s.RegisterService(&DataNodeService_ServiceDesc, srv)
}

func _DataNodeService_WriteChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataNodeServiceServer).WriteChunk(&dataNodeServiceWriteChunkServer{ServerStream: stream})
}

type DataNodeService_WriteChunkServer interface {
	SendAndClose(*ChunkWriteResponse) error
	Recv() (*ChunkWriteRequest, error)
	grpc.ServerStream
}

type dataNodeServiceWriteChunkServer struct {
	grpc.ServerStream
}

func (x *dataNodeServiceWriteChunkServer) SendAndClose(m *ChunkWriteResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dataNodeServiceWriteChunkServer) Recv() (*ChunkWriteRequest, error) {
	m := new(ChunkWriteRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DataNodeService_ReadChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChunkReadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataNodeServiceServer).ReadChunk(m, &dataNodeServiceReadChunkServer{ServerStream: stream})
}

type DataNodeService_ReadChunkServer interface {
	Send(*ChunkReadResponse) error
	grpc.ServerStream
}

type dataNodeServiceReadChunkServer struct {
	grpc.ServerStream
}

func (x *dataNodeServiceReadChunkServer) Send(m *ChunkReadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DataNodeService_DeleteChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNodeServiceServer).DeleteChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataNodeService_DeleteChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNodeServiceServer).DeleteChunk(ctx, req.(*DeleteChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataNodeService_ServiceDesc is the grpc.ServiceDesc for DataNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dfs.v1.DataNodeService",
	HandlerType: (*DataNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteChunk",
			Handler:    _DataNodeService_DeleteChunk_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WriteChunk",
			Handler:       _DataNodeService_WriteChunk_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ReadChunk",
			Handler:       _DataNodeService_ReadChunk_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dfs.proto",
}

const (
	NodeControlService_Heartbeat_FullMethodName    = "/dfs.v1.NodeControlService/Heartbeat"
	NodeControlService_ReportChunks_FullMethodName = "/dfs.v1.NodeControlService/ReportChunks"
)

// NodeControlServiceClient is the client API for NodeControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeControlServiceClient interface {
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	ReportChunks(ctx context.Context, in *ReportChunksRequest, opts ...grpc.CallOption) (*ReportChunksResponse, error)
}

type nodeControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeControlServiceClient(cc grpc.ClientConnInterface) NodeControlServiceClient {
	return &nodeControlServiceClient{cc}
}

func (c *nodeControlServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, NodeControlService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlServiceClient) ReportChunks(ctx context.Context, in *ReportChunksRequest, opts ...grpc.CallOption) (*ReportChunksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportChunksResponse)
	err := c.cc.Invoke(ctx, NodeControlService_ReportChunks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeControlServiceServer is the server API for NodeControlService service.
// All implementations must embed UnimplementedNodeControlServiceServer
// for forward compatibility
type NodeControlServiceServer interface {
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	ReportChunks(context.Context, *ReportChunksRequest) (*ReportChunksResponse, error)
	mustEmbedUnimplementedNodeControlServiceServer()
}

// UnimplementedNodeControlServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNodeControlServiceServer struct {
}

func (UnimplementedNodeControlServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedNodeControlServiceServer) ReportChunks(context.Context, *ReportChunksRequest) (*ReportChunksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportChunks not implemented")
}
func (UnimplementedNodeControlServiceServer) mustEmbedUnimplementedNodeControlServiceServer() {}

// UnsafeNodeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeControlServiceServer will
// result in compilation errors.
type UnsafeNodeControlServiceServer interface {
	mustEmbedUnimplementedNodeControlServiceServer()
}

func RegisterNodeControlServiceServer(s grpc.ServiceRegistrar, srv NodeControlServiceServer) {
	s.RegisterService(&NodeControlService_ServiceDesc, srv)
}

func _NodeControlService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControlService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControlService_ReportChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportChunksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServiceServer).ReportChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControlService_ReportChunks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServiceServer).ReportChunks(ctx, req.(*ReportChunksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeControlService_ServiceDesc is the grpc.ServiceDesc for NodeControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dfs.v1.NodeControlService",
	HandlerType: (*NodeControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _NodeControlService_Heartbeat_Handler,
		},
		{
			MethodName: "ReportChunks",
			Handler:    _NodeControlService_ReportChunks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dfs.proto",
}
