// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: probos/dfs.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_probos_dfs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_probos_dfs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_probos_dfs_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UploadFileRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_probos_dfs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_probos_dfs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_probos_dfs_proto_rawDescGZIP(), []int{1}
}

func (x *UploadFileResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UploadFileResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_probos_dfs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_probos_dfs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_probos_dfs_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_probos_dfs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_probos_dfs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_probos_dfs_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	OwnerId       int64                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_probos_dfs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_probos_dfs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_probos_dfs_proto_rawDescGZIP(), []int{4}
}

func (x *ListFilesRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ListFilesRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	OwnerId       int64                  `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Count         int64                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_probos_dfs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_probos_dfs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_probos_dfs_proto_rawDescGZIP(), []int{5}
}

func (x *ListFilesResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListFilesResponse) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ListFilesResponse) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *ListFilesResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       int64                  `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_probos_dfs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_probos_dfs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_probos_dfs_proto_rawDescGZIP(), []int{6}
}

func (x *GetFileRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *GetFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       int64                  `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Chunks        []*ChunkMetaData       `protobuf:"bytes,4,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_probos_dfs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_probos_dfs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_probos_dfs_proto_rawDescGZIP(), []int{7}
}

func (x *GetFileResponse) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *GetFileResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetFileResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetFileResponse) GetChunks() []*ChunkMetaData {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type ChunkMetaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkMetaData) Reset() {
	*x = ChunkMetaData{}
	mi := &file_probos_dfs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkMetaData) ProtoMessage() {}

func (x *ChunkMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_probos_dfs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkMetaData.ProtoReflect.Descriptor instead.
func (*ChunkMetaData) Descriptor() ([]byte, []int) {
	return file_probos_dfs_proto_rawDescGZIP(), []int{8}
}

func (x *ChunkMetaData) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ChunkMetaData) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChunkMetaData) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type AllocateChunksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateChunksRequest) Reset() {
	*x = AllocateChunksRequest{}
	mi := &file_probos_dfs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateChunksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateChunksRequest) ProtoMessage() {}

func (x *AllocateChunksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_probos_dfs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateChunksRequest.ProtoReflect.Descriptor instead.
func (*AllocateChunksRequest) Descriptor() ([]byte, []int) {
	return file_probos_dfs_proto_rawDescGZIP(), []int{9}
}

func (x *AllocateChunksRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *AllocateChunksRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AllocateChunksRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type AllocateChunksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Chunks        []*ChunkLocation       `protobuf:"bytes,2,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateChunksResponse) Reset() {
	*x = AllocateChunksResponse{}
	mi := &file_probos_dfs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateChunksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateChunksResponse) ProtoMessage() {}

func (x *AllocateChunksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_probos_dfs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateChunksResponse.ProtoReflect.Descriptor instead.
func (*AllocateChunksResponse) Descriptor() ([]byte, []int) {
	return file_probos_dfs_proto_rawDescGZIP(), []int{10}
}

func (x *AllocateChunksResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *AllocateChunksResponse) GetChunks() []*ChunkLocation {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type GetChunkLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkLocationRequest) Reset() {
	*x = GetChunkLocationRequest{}
	mi := &file_probos_dfs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkLocationRequest) ProtoMessage() {}

func (x *GetChunkLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_probos_dfs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkLocationRequest.ProtoReflect.Descriptor instead.
func (*GetChunkLocationRequest) Descriptor() ([]byte, []int) {
	return file_probos_dfs_proto_rawDescGZIP(), []int{11}
}

func (x *GetChunkLocationRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type GetChunkLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locs          []*ChunkLocation       `protobuf:"bytes,1,rep,name=locs,proto3" json:"locs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkLocationResponse) Reset() {
	*x = GetChunkLocationResponse{}
	mi := &file_probos_dfs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkLocationResponse) ProtoMessage() {}

func (x *GetChunkLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_probos_dfs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkLocationResponse.ProtoReflect.Descriptor instead.
func (*GetChunkLocationResponse) Descriptor() ([]byte, []int) {
	return file_probos_dfs_proto_rawDescGZIP(), []int{12}
}

func (x *GetChunkLocationResponse) GetLocs() []*ChunkLocation {
	if x != nil {
		return x.Locs
	}
	return nil
}

type ChunkLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Replicas      []*DataNodeEndpoint    `protobuf:"bytes,3,rep,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkLocation) Reset() {
	*x = ChunkLocation{}
	mi := &file_probos_dfs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkLocation) ProtoMessage() {}

func (x *ChunkLocation) ProtoReflect() protoreflect.Message {
	mi := &file_probos_dfs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkLocation.ProtoReflect.Descriptor instead.
func (*ChunkLocation) Descriptor() ([]byte, []int) {
	return file_probos_dfs_proto_rawDescGZIP(), []int{13}
}

func (x *ChunkLocation) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ChunkLocation) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChunkLocation) GetReplicas() []*DataNodeEndpoint {
	if x != nil {
		return x.Replicas
	}
	return nil
}

type DataNodeEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataNodeEndpoint) Reset() {
	*x = DataNodeEndpoint{}
	mi := &file_probos_dfs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataNodeEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataNodeEndpoint) ProtoMessage() {}

func (x *DataNodeEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_probos_dfs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataNodeEndpoint.ProtoReflect.Descriptor instead.
func (*DataNodeEndpoint) Descriptor() ([]byte, []int) {
	return file_probos_dfs_proto_rawDescGZIP(), []int{14}
}

func (x *DataNodeEndpoint) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DataNodeEndpoint) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ChunkWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Eof           bool                   `protobuf:"varint,4,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkWriteRequest) Reset() {
	*x = ChunkWriteRequest{}
	mi := &file_probos_dfs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkWriteRequest) ProtoMessage() {}

func (x *ChunkWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_probos_dfs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkWriteRequest.ProtoReflect.Descriptor instead.
func (*ChunkWriteRequest) Descriptor() ([]byte, []int) {
	return file_probos_dfs_proto_rawDescGZIP(), []int{15}
}

func (x *ChunkWriteRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ChunkWriteRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChunkWriteRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ChunkWriteRequest) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type ChunkWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkWriteResponse) Reset() {
	*x = ChunkWriteResponse{}
	mi := &file_probos_dfs_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkWriteResponse) ProtoMessage() {}

func (x *ChunkWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_probos_dfs_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkWriteResponse.ProtoReflect.Descriptor instead.
func (*ChunkWriteResponse) Descriptor() ([]byte, []int) {
	return file_probos_dfs_proto_rawDescGZIP(), []int{16}
}

func (x *ChunkWriteResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ChunkReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        uint64                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkReadRequest) Reset() {
	*x = ChunkReadRequest{}
	mi := &file_probos_dfs_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkReadRequest) ProtoMessage() {}

func (x *ChunkReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_probos_dfs_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkReadRequest.ProtoReflect.Descriptor instead.
func (*ChunkReadRequest) Descriptor() ([]byte, []int) {
	return file_probos_dfs_proto_rawDescGZIP(), []int{17}
}

func (x *ChunkReadRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ChunkReadRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ChunkReadRequest) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type ChunkReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,2,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkReadResponse) Reset() {
	*x = ChunkReadResponse{}
	mi := &file_probos_dfs_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkReadResponse) ProtoMessage() {}

func (x *ChunkReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_probos_dfs_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkReadResponse.ProtoReflect.Descriptor instead.
func (*ChunkReadResponse) Descriptor() ([]byte, []int) {
	return file_probos_dfs_proto_rawDescGZIP(), []int{18}
}

func (x *ChunkReadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChunkReadResponse) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type DeleteChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChunkRequest) Reset() {
	*x = DeleteChunkRequest{}
	mi := &file_probos_dfs_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChunkRequest) ProtoMessage() {}

func (x *DeleteChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_probos_dfs_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChunkRequest.ProtoReflect.Descriptor instead.
func (*DeleteChunkRequest) Descriptor() ([]byte, []int) {
	return file_probos_dfs_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

type DeleteChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChunkResponse) Reset() {
	*x = DeleteChunkResponse{}
	mi := &file_probos_dfs_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChunkResponse) ProtoMessage() {}

func (x *DeleteChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_probos_dfs_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChunkResponse.ProtoReflect.Descriptor instead.
func (*DeleteChunkResponse) Descriptor() ([]byte, []int) {
	return file_probos_dfs_proto_rawDescGZIP(), []int{20}
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	CapacityBytes int64                  `protobuf:"varint,3,opt,name=capacity_bytes,json=capacityBytes,proto3" json:"capacity_bytes,omitempty"`
	UsedBytes     int64                  `protobuf:"varint,4,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_probos_dfs_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_probos_dfs_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_probos_dfs_proto_rawDescGZIP(), []int{21}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *HeartbeatRequest) GetCapacityBytes() int64 {
	if x != nil {
		return x.CapacityBytes
	}
	return 0
}

func (x *HeartbeatRequest) GetUsedBytes() int64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_probos_dfs_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_probos_dfs_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_probos_dfs_proto_rawDescGZIP(), []int{22}
}

type ReportChunksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ChunkIds      []string               `protobuf:"bytes,2,rep,name=chunk_ids,json=chunkIds,proto3" json:"chunk_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportChunksRequest) Reset() {
	*x = ReportChunksRequest{}
	mi := &file_probos_dfs_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportChunksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportChunksRequest) ProtoMessage() {}

func (x *ReportChunksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_probos_dfs_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportChunksRequest.ProtoReflect.Descriptor instead.
func (*ReportChunksRequest) Descriptor() ([]byte, []int) {
	return file_probos_dfs_proto_rawDescGZIP(), []int{23}
}

func (x *ReportChunksRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportChunksRequest) GetChunkIds() []string {
	if x != nil {
		return x.ChunkIds
	}
	return nil
}

type ReportChunksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportChunksResponse) Reset() {
	*x = ReportChunksResponse{}
	mi := &file_probos_dfs_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportChunksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportChunksResponse) ProtoMessage() {}

func (x *ReportChunksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_probos_dfs_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportChunksResponse.ProtoReflect.Descriptor instead.
func (*ReportChunksResponse) Descriptor() ([]byte, []int) {
	return file_probos_dfs_proto_rawDescGZIP(), []int{24}
}

var File_probos_dfs_proto protoreflect.FileDescriptor

const file_probos_dfs_proto_rawDesc = "" +
	"\n" +
	"\x10probos/dfs.proto\x12\x06dfs.v1\"W\n" +
	"\x11UploadFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"D\n" +
	"\x12UploadFileResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse\"'\n" +
	"\x11DeleteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\".\n" +
	"\x12DeleteFileResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"C\n" +
	"\x10ListFilesRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x03R\aownerId\"n\n" +
	"\x11ListFilesResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\x03R\aownerId\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\"?\n" +
	"\x0eGetFileRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\x03R\aownerId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x83\x01\n" +
	"\x0fGetFileResponse\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\x03R\aownerId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12-\n" +
	"\x06chunks\x18\x04 \x03(\v2\x15.dfs.v1.ChunkMetaDataR\x06chunks\"T\n" +
	"\rChunkMetaData\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"Z\n" +
	"\x15AllocateChunksRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\"`\n" +
	"\x16AllocateChunksResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12-\n" +
	"\x06chunks\x18\x02 \x03(\v2\x15.dfs.v1.ChunkLocationR\x06chunks\"2\n" +
	"\x17GetChunkLocationRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"E\n" +
	"\x18GetChunkLocationResponse\x12)\n" +
	"\x04locs\x18\x01 \x03(\v2\x15.dfs.v1.ChunkLocationR\x04locs\"v\n" +
	"\rChunkLocation\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x124\n" +
	"\breplicas\x18\x03 \x03(\v2\x18.dfs.v1.DataNodeEndpointR\breplicas\"E\n" +
	"\x10DataNodeEndpoint\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"l\n" +
	"\x11ChunkWriteRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12\x10\n" +
	"\x03eof\x18\x04 \x01(\bR\x03eof\"$\n" +
	"\x12ChunkWriteResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"]\n" +
	"\x10ChunkReadRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x04R\x06length\"9\n" +
	"\x11ChunkReadResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x02 \x01(\bR\x03eof\"/\n" +
	"\x12DeleteChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\"\x15\n" +
	"\x13DeleteChunkResponse\"\x8b\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12%\n" +
	"\x0ecapacity_bytes\x18\x03 \x01(\x03R\rcapacityBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x04 \x01(\x03R\tusedBytes\"\x13\n" +
	"\x11HeartbeatResponse\"K\n" +
	"\x13ReportChunksRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tchunk_ids\x18\x02 \x03(\tR\bchunkIds\"\x16\n" +
	"\x14ReportChunksResponse2\xc5\x03\n" +
	"\vMetaService\x12F\n" +
	"\rUploadRequest\x12\x19.dfs.v1.UploadFileRequest\x1a\x1a.dfs.v1.UploadFileResponse\x12F\n" +
	"\rDeleteRequest\x12\x19.dfs.v1.DeleteFileRequest\x1a\x1a.dfs.v1.DeleteFileResponse\x12@\n" +
	"\tListFiles\x12\x18.dfs.v1.ListFilesRequest\x1a\x19.dfs.v1.ListFilesResponse\x12:\n" +
	"\aGetFile\x12\x16.dfs.v1.GetFileRequest\x1a\x17.dfs.v1.GetFileResponse\x12O\n" +
	"\x0eAllocateChunks\x12\x1d.dfs.v1.AllocateChunksRequest\x1a\x1e.dfs.v1.AllocateChunksResponse\x12W\n" +
	"\x12GetChunksLocations\x12\x1f.dfs.v1.GetChunkLocationRequest\x1a .dfs.v1.GetChunkLocationResponse2\xe4\x01\n" +
	"\x0fDataNodeService\x12E\n" +
	"\n" +
	"WriteChunk\x12\x19.dfs.v1.ChunkWriteRequest\x1a\x1a.dfs.v1.ChunkWriteResponse(\x01\x12B\n" +
	"\tReadChunk\x12\x18.dfs.v1.ChunkReadRequest\x1a\x19.dfs.v1.ChunkReadResponse0\x01\x12F\n" +
	"\vDeleteChunk\x12\x1a.dfs.v1.DeleteChunkRequest\x1a\x1b.dfs.v1.DeleteChunkResponse2\xa1\x01\n" +
	"\x12NodeControlService\x12@\n" +
	"\tHeartbeat\x12\x18.dfs.v1.HeartbeatRequest\x1a\x19.dfs.v1.HeartbeatResponse\x12I\n" +
	"\fReportChunks\x12\x1b.dfs.v1.ReportChunksRequest\x1a\x1c.dfs.v1.ReportChunksResponseB;Z9github.com/ayushchoudhary-3190/grpc_project/backend/pb;pbb\x06proto3"

var (
	file_probos_dfs_proto_rawDescOnce sync.Once
	file_probos_dfs_proto_rawDescData []byte
)

func file_probos_dfs_proto_rawDescGZIP() []byte {
	file_probos_dfs_proto_rawDescOnce.Do(func() {
		file_probos_dfs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_probos_dfs_proto_rawDesc), len(file_probos_dfs_proto_rawDesc)))
	})
	return file_probos_dfs_proto_rawDescData
}

var file_probos_dfs_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_probos_dfs_proto_goTypes = []any{
	(*UploadFileRequest)(nil),        // 0: dfs.v1.UploadFileRequest
	(*UploadFileResponse)(nil),       // 1: dfs.v1.UploadFileResponse
	(*DeleteFileRequest)(nil),        // 2: dfs.v1.DeleteFileRequest
	(*DeleteFileResponse)(nil),       // 3: dfs.v1.DeleteFileResponse
	(*ListFilesRequest)(nil),         // 4: dfs.v1.ListFilesRequest
	(*ListFilesResponse)(nil),        // 5: dfs.v1.ListFilesResponse
	(*GetFileRequest)(nil),           // 6: dfs.v1.GetFileRequest
	(*GetFileResponse)(nil),          // 7: dfs.v1.GetFileResponse
	(*ChunkMetaData)(nil),            // 8: dfs.v1.ChunkMetaData
	(*AllocateChunksRequest)(nil),    // 9: dfs.v1.AllocateChunksRequest
	(*AllocateChunksResponse)(nil),   // 10: dfs.v1.AllocateChunksResponse
	(*GetChunkLocationRequest)(nil),  // 11: dfs.v1.GetChunkLocationRequest
	(*GetChunkLocationResponse)(nil), // 12: dfs.v1.GetChunkLocationResponse
	(*ChunkLocation)(nil),            // 13: dfs.v1.ChunkLocation
	(*DataNodeEndpoint)(nil),         // 14: dfs.v1.DataNodeEndpoint
	(*ChunkWriteRequest)(nil),        // 15: dfs.v1.ChunkWriteRequest
	(*ChunkWriteResponse)(nil),       // 16: dfs.v1.ChunkWriteResponse
	(*ChunkReadRequest)(nil),         // 17: dfs.v1.ChunkReadRequest
	(*ChunkReadResponse)(nil),        // 18: dfs.v1.ChunkReadResponse
	(*DeleteChunkRequest)(nil),       // 19: dfs.v1.DeleteChunkRequest
	(*DeleteChunkResponse)(nil),      // 20: dfs.v1.DeleteChunkResponse
	(*HeartbeatRequest)(nil),         // 21: dfs.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 22: dfs.v1.HeartbeatResponse
	(*ReportChunksRequest)(nil),      // 23: dfs.v1.ReportChunksRequest
	(*ReportChunksResponse)(nil),     // 24: dfs.v1.ReportChunksResponse
}
var file_probos_dfs_proto_depIdxs = []int32{
	8,  // 0: dfs.v1.GetFileResponse.chunks:type_name -> dfs.v1.ChunkMetaData
	13, // 1: dfs.v1.AllocateChunksResponse.chunks:type_name -> dfs.v1.ChunkLocation
	13, // 2: dfs.v1.GetChunkLocationResponse.locs:type_name -> dfs.v1.ChunkLocation
	14, // 3: dfs.v1.ChunkLocation.replicas:type_name -> dfs.v1.DataNodeEndpoint
	0,  // 4: dfs.v1.MetaService.UploadRequest:input_type -> dfs.v1.UploadFileRequest
	2,  // 5: dfs.v1.MetaService.DeleteRequest:input_type -> dfs.v1.DeleteFileRequest
	4,  // 6: dfs.v1.MetaService.ListFiles:input_type -> dfs.v1.ListFilesRequest
	6,  // 7: dfs.v1.MetaService.GetFile:input_type -> dfs.v1.GetFileRequest
	9,  // 8: dfs.v1.MetaService.AllocateChunks:input_type -> dfs.v1.AllocateChunksRequest
	11, // 9: dfs.v1.MetaService.GetChunksLocations:input_type -> dfs.v1.GetChunkLocationRequest
	15, // 10: dfs.v1.DataNodeService.WriteChunk:input_type -> dfs.v1.ChunkWriteRequest
	17, // 11: dfs.v1.DataNodeService.ReadChunk:input_type -> dfs.v1.ChunkReadRequest
	19, // 12: dfs.v1.DataNodeService.DeleteChunk:input_type -> dfs.v1.DeleteChunkRequest
	21, // 13: dfs.v1.NodeControlService.Heartbeat:input_type -> dfs.v1.HeartbeatRequest
	23, // 14: dfs.v1.NodeControlService.ReportChunks:input_type -> dfs.v1.ReportChunksRequest
	1,  // 15: dfs.v1.MetaService.UploadRequest:output_type -> dfs.v1.UploadFileResponse
	3,  // 16: dfs.v1.MetaService.DeleteRequest:output_type -> dfs.v1.DeleteFileResponse
	5,  // 17: dfs.v1.MetaService.ListFiles:output_type -> dfs.v1.ListFilesResponse
	7,  // 18: dfs.v1.MetaService.GetFile:output_type -> dfs.v1.GetFileResponse
	10, // 19: dfs.v1.MetaService.AllocateChunks:output_type -> dfs.v1.AllocateChunksResponse
	12, // 20: dfs.v1.MetaService.GetChunksLocations:output_type -> dfs.v1.GetChunkLocationResponse
	16, // 21: dfs.v1.DataNodeService.WriteChunk:output_type -> dfs.v1.ChunkWriteResponse
	18, // 22: dfs.v1.DataNodeService.ReadChunk:output_type -> dfs.v1.ChunkReadResponse
	20, // 23: dfs.v1.DataNodeService.DeleteChunk:output_type -> dfs.v1.DeleteChunkResponse
	22, // 24: dfs.v1.NodeControlService.Heartbeat:output_type -> dfs.v1.HeartbeatResponse
	24, // 25: dfs.v1.NodeControlService.ReportChunks:output_type -> dfs.v1.ReportChunksResponse
	15, // [15:26] is the sub-list for method output_type
	4,  // [4:15] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_probos_dfs_proto_init() }
func file_probos_dfs_proto_init() {
	if File_probos_dfs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_probos_dfs_proto_rawDesc), len(file_probos_dfs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_probos_dfs_proto_goTypes,
		DependencyIndexes: file_probos_dfs_proto_depIdxs,
		MessageInfos:      file_probos_dfs_proto_msgTypes,
	}.Build()
	File_probos_dfs_proto = out.File
	file_probos_dfs_proto_goTypes = nil
	file_probos_dfs_proto_depIdxs = nil
}
